version: '3.9'

services:
  ghost:
    volumes:
      - ghosttheme-sync:/var/lib/ghost/content/themes/seek:nocopy
    build:
      context: ~/c/
      dockerfile: ./docker-ghost/blog/GhostDockerfile
    environment:
      NODE_ENV: ${ENVIRONMENT:-production}
      url: ${BLOG_URL}
      database__client: mysql
      database__connection__host: ${MYSQL_HOST}
      database__connection__database: ${MYSQL_DB}
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      mail__transport: ${MAIL_TRANSPORT}
      mail__options__service: ${MAIL_SERVICE}
      mail__options__host: ${MAIL_HOST}
      mail__options__port: ${MAIL_PORT}
      mail__options__secureConnection: ${MAIL_SECURE}
      mail__options__auth__user: ${MAIL_USER}
      mail__options__auth__pass: ${MAIL_PASSWORD}
    restart: always

  nginx:
    build:
      context: ~/c/docker-ghost
      dockerfile: ./blog/NginxDockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ghost


volumes:
  ghosttheme-sync:
    external: true